#!/bin/bash
cd "$(dirname "$0")/docker"

abortMsg() {
	echo 1>&2 "ERROR: $*"
	exit 1
}

([ -f tk4-_v1.00_current.zip ] || wget https://github.com/skissane/mvs38j/releases/download/v1.0.8.0/tk4-_v1.00_current.zip ) ||
	abortMsg "Download of TK4- failed"

docker build -t mvs38j .
